Cybereum/Controllers/ActivityController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Cybereum.Models;
using Cybereum.Filters;
using System.Threading.Tasks;
using Gremlin.Net.Driver;
using Gremlin.Net.Structure.IO.GraphSON;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Configuration;

namespace Cybereum.Controllers
{
    [Authorize]
    public class ActivityController : Controller
    {
        private cybereumEntities db = new cybereumEntities();

        // GET: Activity
        [Authorize]
        [SessionTimeout]
        public ActionResult Index(string projectid)
        {
            //TempData["ProjectId"] = projectid;
            //ViewBag.projectid = TempData["ProjectId"];
            //TempData.Keep();
            if (projectid == string.Empty)
            {
                ViewBag.projectid = Convert.ToInt32(Session["ProjectId"]);
                Session["ProjectId"] = ViewBag.projectid;
            }
            else
            {
                ViewBag.projectid = projectid;
                Session["ProjectId"] = projectid;
            }
            return View();
        }


        public ActionResult Addrecord(string Id)
        {
            ViewBag.Message = "Edit Activity";
            //ProjectActivity activity = new ProjectActivity();

            var activity = getactivitybyid(Id);            
            return RedirectToAction("Create", activity.Result);
        }


        public async Task<JsonResult> activitylist(string projectid)
        {
            List<ProjectActivity> list = new List<ProjectActivity>();
            try
            {
                var gremlinScript = "g.V().has('activity','projectid','" + projectid + "').project('id','activityname','startdate','enddate','durations','ismilestone','createdby','createdusername','createdon','projectid')" +
                                    ".by(id()).by(values('activityname')).by(values('startdate')).by(values('enddate')).by(values('durations')).by(values('ismilestone')).by(values('createdby')).by(values('createdusername')).by(values('createdon')).by(values('projectid'))";
                try
                {
                    var results = IGUtilities.ExecuteGremlinScript(gremlinScript);
                    string pList = JsonConvert.SerializeObject(results);
                    List<ProjectActivity> people = JsonConvert.DeserializeObject<List<ProjectActivity>>(pList);

                    list = people;

                    var projectresult = this.Json(new { data = list, recordsTotal = list.Count(), recordsFiltered = list.Count() }, JsonRequestBehavior.AllowGet);
                    return projectresult;
                }
                catch (Exception ex)
                {
                    throw ex;
                }
                //}
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return null;
        }

        public async Task<ProjectActivity> getactivitybyid(string id)
        {
            ProjectActivity activity = new ProjectActivity();
            try
            {
                var gremlinScript = "g.V().has('activity','id','" + id + "').project('id','activityname','startdate','enddate','durations','ismilestone','createdby','createdusername','createdon','projectid','predecessors').by(id()).by(values('activityname')).by(values('startdate')).by(values('enddate')).by(values('durations')).by(values('ismilestone')).by(values('createdby')).by(values('createdusername')).by(values('createdon')).by(values('projectid')).by(values('predecessors').fold())";
                try
                {
                    var results = IGUtilities.ExecuteGremlinScript(gremlinScript);
                    foreach (var result in results)
                    {
                        activity.id = result["id"].ToString();
                        activity.projectid = result["projectid"].ToString();
                        activity.activityname = result["activityname"].ToString();
                        activity.startdate = Convert.ToDateTime(result["startdate"]);
                        activity.enddate = Convert.ToDateTime(result["enddate"]);
                        activity.ismilestone = Convert.ToBoolean(result["ismilestone"]);
                        activity.durations = Convert.ToInt64(result["durations"]);

                        var predecessors = result["predecessors"];
                        var stringlist = JsonConvert.SerializeObject(predecessors);
                        var jArray = JArray.Parse(stringlist);
                        string tasks = string.Empty;
                        foreach (string item in jArray)
                        {
                            tasks = tasks + item + ",";
                        }
                        if (tasks != "") tasks = tasks.Remove(tasks.LastIndexOf(",")).ToString();
                        if (tasks.ToString() != string.Empty)
                        {
                            string[] ints = tasks.Split(',').ToArray();
                            activity.Predecessors = ints;
                        }
                        //activity.Predecessors = result["predecessors"].ToString();

                        activity.createdby = result["createdby"].ToString();
                        activity.createdusername = result["createdusername"].ToString();
                        activity.createdon = Convert.ToDateTime(result["createdon"]);
                    }
                    return activity;
                }
                catch (Exception ex)
                {
                    throw ex;
                }
                //}
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return null;
        }

        [Authorize]
        [SessionTimeout]
        //[Route("Activity/Create/{projectid}/{activityid}")]
        public ActionResult Create(string activityid, string projectid, ProjectActivity Activity)
        {
            if (Activity.id != null)
            {
                var result1 = getactivitybyid(Activity.id);
                Activity = result1.Result;
            }

            ViewBag.HasDate = false;
            if (projectid == null)
            {
                ViewBag.projectid = Convert.ToInt32(Session["ProjectId"]);
                Session["ProjectId"] = ViewBag.projectid;
            }
            else
            {
                ViewBag.projectid = projectid;
                Session["ProjectId"] = projectid;
            }

            if (activityid != null)
            {
                var gremlinScript = "g.V().has('activity','id','" + activityid + "').project('startdate','enddate').by(values('startdate')).by(values('enddate'))";
                var result = IGUtilities.ExecuteGremlinScript(gremlinScript);
                if (result.Count > 0)
                {
                    foreach (var item in result)
                    {
                        ViewBag.HasDate = false;
                        DateTime dt1 = Convert.ToDateTime(item["enddate"]);
                        dt1 = dt1.AddBusinessDays(1);
                        Activity.startdate = dt1;
                        Activity.enddate = dt1;
                    }
                }
                else
                {
                    gremlinScript = "g.V().has('project','id','" + projectid + "').project('startdate','enddate').by(values('startdate')).by(values('enddate'))";
                    var resultProject = IGUtilities.ExecuteGremlinScript(gremlinScript);
                    if (resultProject.Count > 0)
                    {
                        foreach (var item in resultProject)
                        {
                            ViewBag.HasDate = false;
                            DateTime dt1 = Convert.ToDateTime(item["startdate"]);
                            //dt1 = dt1.AddDays(1);
                            Activity.startdate = dt1;
                            Activity.enddate = dt1;
                        }
                    }
                    else
                    {
                        Activity.startdate = DateTime.Today;
                        Activity.enddate = DateTime.Today;
                    }
                }
            }
            else if (Activity.id == null)
            {
                var gremlinScript = "g.V().has('activity','projectid','" + projectid + "').order().by('enddate',decr).limit(1).project('startdate','enddate').by(values('startdate')).by(values('enddate'))";
                var result = IGUtilities.ExecuteGremlinScript(gremlinScript);
                if (result.Count > 0)
                {
                    foreach (var item in result)
                    {
                        ViewBag.HasDate = false;
                        DateTime dt1 = Convert.ToDateTime(item["enddate"]);
                        dt1 = dt1.AddBusinessDays(1);
                        Activity.startdate = dt1;
                        Activity.enddate = dt1;
                    }
                }
                else
                {
                    Activity.startdate = DateTime.Today;
                    Activity.enddate = DateTime.Today;
                }
            }

            int pmuserid = Convert.ToInt32(Session["LoggedInUserId"]);
            int roleid = Convert.ToInt32(Session["RoleId"]);
            List<SelectListItem> user = Filluser(pmuserid, roleid);
            ViewBag.createdby = user;

            List<SelectListItem> predecessors = FillActivity(projectid, activityid, Activity);
            ViewBag.predecessors = predecessors;

            return View(Activity);
        }

        public JsonResult GetEnddate(DateTime startDate, int id)
        {
            var record = IGUtilities.CalculateDays(startDate, id);

Cybereum/Views/Activity/Create.cshtml
@model Cybereum.Models.ProjectActivity

@{
    ViewBag.Title = "Add/Edit Activity";
}

<style type="text/css">
    .error {
        color: red;
        display: none;
    }

    #divLoader {
        position: fixed;
        display: block;
        width: 100%;
        height: 100%;
        top: 0;
        left: 0;
        text-align: center;
        opacity: 0.7;
        background-color: #fff;
        z-index: 99;
    }

    #loading-image {
        position: absolute;
        top: 50%;
        left: 50%;
        z-index: 100;
    }
</style>

<div class="row">
    <div id="divLoader" style="display:none;">
        <img id="loading-image" src="~/images/Spinner.gif" alt="Loader" />
    </div>
    <div class="col-xl-12 col-lg-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Add/Edit Activity</h4>
            </div>
            <div class="card-body">
                <div class="basic-form">
                    @using (Html.BeginForm("Create", "Activity", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()

                        @*<div class="form-horizontal">
                            <hr />*@
                        <span class="text-danger" style="align-items:center;">
                            @ViewBag.Message
                            @Html.HiddenFor(model => model.id)
                            @Html.HiddenFor(model => model.projectid)
                            @*@Html.HiddenFor(model => model.createdby)*@
                            @Html.HiddenFor(model => model.createdon)
                            @Html.HiddenFor(model => model.Predecessors)
                        </span>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                @Html.LabelFor(model => model.activityname, "Activity Name", htmlAttributes: new { @class = "" })
                                @Html.EditorFor(model => model.activityname, new { htmlAttributes = new { @class = "form-control", autocomplete = "off" } })
                                @Html.ValidationMessageFor(model => model.activityname, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group col-md-6">
                                @Html.LabelFor(model => model.startdate, "Start Date", htmlAttributes: new { @class = "" })
                                @*@if (Convert.ToBoolean(ViewBag.HasDate))
                                {*@
                                    @Html.TextBoxFor(model => model.startdate, new { @type = "date", @class = "form-control datepicker", @Value = Model.startdate.ToString("yyyy-MM-dd")})
                                @*}
                                else
                                {
                                    @Html.TextBoxFor(model => model.startdate, new { @type = "date", @class = "form-control datepicker", @Value = Model.startdate.ToString("yyyy-MM-dd") })
                                }*@
                                @Html.ValidationMessageFor(model => model.startdate, "", new { @class = "text-danger" })

                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                @Html.LabelFor(model => model.durations, "Duration", htmlAttributes: new { @class = "" })

                                @Html.TextBoxFor(model => model.durations, new { @class = "form-control", autocomplete = "off" })
                                @Html.ValidationMessageFor(model => model.durations, "", new { @class = "text-danger" })

                            </div>
                            <div class="form-group col-md-6">
                                @Html.LabelFor(model => model.enddate, "End Date", htmlAttributes: new { @class = "" })

                                @Html.TextBoxFor(model => model.enddate, new { @type = "date", @class = "form-control datepicker", @Value = Model.enddate.ToString("yyyy-MM-dd")})
                                @Html.ValidationMessageFor(model => model.enddate, "", new { @class = "text-danger" })

                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                @Html.LabelFor(model => model.ismilestone, "Is Milestone?", htmlAttributes: new { @class = "" })

                                @Html.CheckBoxFor(model => model.ismilestone)

                            </div>
                            <div class="form-group col-md-6">
                                @Html.Label("Predecessors", htmlAttributes: new { @class = "" })
                                @*@Html.DropDownList("predecessors", ViewBag.predecessors as SelectList, htmlAttributes: new { @class = "form-control", multiple = "multiple" })*@
                                @*<div style="height: 300px; overflow-y: scroll;">
                                    @if (ViewBag.predecessors != null)
                                    {
                                        foreach (var item in ViewBag.predecessors)
                                        {
                                            <input id="@item.Value" type="checkbox" name="Predecessors" value="@item.Value" checked="@item.Selected" class="checkbox" onclick="Selectitem()" />
                                            <label for="@item.Value">
                                                @item.Text
                                            </label>
                                                <br />
                                        }
                                    }
                                </div>*@                                
                                <div>
                                        <select id="mypredecessors" multiple="multiple" class="form-control" name="Predecessors" onchange="GetSelectedPredecessors()">
                                            @if (ViewBag.predecessors != null)
                                            {
                                                foreach (var item in ViewBag.predecessors)
                                                {
                                                    if (item.Text != null)
                                                    {
                                                        if (item.Selected == true)
                                                        {
                                                            <option id="@item.Value" value="@item.Value" selected="selected">
                                                                @item.Text
                                                            </option>
                                                        }
                                                        else
                                                        {
                                                            <option id="@item.Value" value="@item.Value">
                                                                @item.Text
                                                            </option>
                                                        }
                                                    }
                                                }
                                            }
                                        </select>
                                    </div>

                            </div>
                        </div>
                        <div class="form-group col-md-6">
                            @if (Convert.ToInt32(Session["RoleId"]) == 1)
                            {
                                <div class="form-group col-md-6">
                                    @Html.LabelFor(model => model.createdby, "Project Manager", htmlAttributes: new { @class = "" })
                                    @*<div class="col-md-10">*@
                                    @Html.DropDownList("createdby", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.createdby, "", new { @class = "text-danger" })
                                    @*</div>*@
                                </div>
                            }
                            else
                            {
                                @Html.HiddenFor(model => model.createdby)
                            }
                        </div>
                        <div class="row" style="padding-top: 30px;">
                            <div class="col-6">
                                <h4>
                                    @Html.ActionLink("Back to List", "Index", new
                                       {
                                           projectid = ViewBag.projectid
                                       })
                                </h4>
                            </div>
                            <div class="col-6">
                                @*<button type="button" class="btn btn" style="background-color: #0D2136; color: white;" data-dismiss="modal" onclick="history.go(-1); return false;">Close</button>*@
                                <input type="submit" name="btnSubmit" value="Save" class="btn btn" style="background-color: #0D2136; color: white;" />
                            </div>

                        </div>
                                @*</div>*@
                    }
                </div>
            </div>
        </div>
    </div>
</div>


@Scripts.Render("~/bundles/jquery")
<script type="text/javascript">
    $(document).ajaxSend(function () {
        //$("#overlay").fadeIn(300);
    });

    function Selectitem() {
        debugger;
        $("#divLoader").show();
        var $element = $(this);
        var id = $element.attr('id');
        var arr = [];
        $.each($("input[name='Predecessors']:checked"), function () {
            arr.push($(this).val());
        });        
        $.ajax({
            url: '/Activity/GetPredecesdate',
            data: { id: arr },
            traditional: true,
            success: function (data) {
                debugger;
                $("#divLoader").hide();
                var date = new Date(parseInt(data.substr(6)));
                var month = ("0" + (date.getMonth() + 1)).slice(-2);
                date = date.getFullYear() + '-' + month + '-' + ("0" + date.getDate()).slice(-2);
                $('#startdate').val(date);
                $('#enddate').val(date);
            }
        });

    }


    function GetSelectedPredecessors() {
        debugger;
        $("#divLoader").show();
        var arr = [];
        $("#mypredecessors option:selected").each(function () {
            arr.push($(this).val());
        });
        if (arr) {
            $.ajax({
                url: '/Activity/GetPredecesdate',
                data: { id: arr },
                traditional: true,
                success: function (data) {
                    debugger;
                    $("#divLoader").hide();
                    var date = new Date(parseInt(data.substr(6)));
                    var month = ("0" + (date.getMonth() + 1)).slice(-2);
                    date = date.getFullYear() + '-' + month + '-' + ("0" + date.getDate()).slice(-2);
                    $('#startdate').val(date);
                    $('#enddate').val(date);                    
                }
            });
        }
        else {
            $("#divLoader").hide();
            alert("Please select at least one predecessor");
        };
    }

    $(document).ready(function () {
        debugger;

        $('#durations').change(function () {
            var recordId = this.value;
            var startdate = $("#startdate").val();
            $.getJSON("/Activity/GetEnddate",
                {
                    startDate: startdate,
                    id: recordId
                },
                function (data) {
                    debugger;
                    var date = new Date(parseInt(data.substr(6)));
                    var month = ("0" + (date.getMonth() + 1)).slice(-2);
                    date = date.getFullYear() + '-' + month + '-' + ("0" + date.getDate()).slice(-2);
                    $('#enddate').val(date);
                });
        });

        $(function () {
            //$("#startdate").datepicker();
            $("#startdate").on('change', function () {
                debugger;
                var startdate = $("#startdate").val();
                var date = $("#enddate").val();
                if (date != "") {
                    if (date < startdate) {
                        alert('End date must be greater than Start date');
                        $(this).val('');
                    }
                }
            });
        });


        $(function () {
            $("#enddate").on('change', function () {
                debugger;
                var date = $("#enddate").val();
                var startdate = $("#startdate").val();
                if (date != "") {
                    if (date < startdate) {
                        alert('End date must be greater than Start date');
                        $(this).val('');
                    }
                }
            });
        });

        $('#checkBoxAll').click(function () {
            if ($(this).is(":checked")) {
                $(".chkCheckBoxId").prop("checked", true)
            }
            else {
                $(".chkCheckBoxId").prop("checked", false)
            }
        });

    });
</script>