Cybereum/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Cybereum.Models;
using Cybereum.Filters;
using Newtonsoft.Json;
using Newtonsoft.Json;
using System.Threading.Tasks;
using Gremlin.Net.Driver;
using System.IO;
using Gremlin.Net.Structure.IO.GraphSON;
using Newtonsoft.Json.Linq;
using Cybereum.Services;
using System.Configuration;
using System.Net.Http;
using System.Text;
using System.Collections.Specialized;
using System.Web.Script.Serialization;
using Microsoft.Graph;
using System.Net.Mime;
using Microsoft.Azure.Documents;
using Microsoft.Azure.Documents.Client;

namespace Cybereum.Controllers
{
    [Authorize]
    public class ProjectController : Controller
    {
        private cybereumEntities db = new cybereumEntities();


        [Authorize]
        [SessionTimeout]
        // GET: Project
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        [SessionTimeout]
        public ActionResult List()
        {
            return View();
        }

        [Authorize]
        //[Authorize(Roles ="Admin,ProjectManager,OrganizationManager,SeniorProjectManager")]
        [SessionTimeout]
        public ActionResult OrganizationProjectList(string organization)
        {
            //var x = getproject();
            Session["Organization"] = organization;
            return View();
        }

        public async Task<Project> getprojectbyid(string id)
        {
            Project project = new Project();
            try
            {
                try
                {
                    var results = GetProjectbyID(id);

                    foreach (var result in results)
                    {
                        project.projectid = result["id"].ToString();
                        project.projectname = result["projectname"].ToString();
                        project.startdate = Convert.ToDateTime(result["startdate"]);
                        project.enddate = Convert.ToDateTime(result["enddate"]);
                        //project.type = result["type"].ToString();
                        project.noofresource = result["noofresource"].ToString();
                        project.projectcost = result["projectcost"].ToString();
                        project.createdby = Convert.ToInt16(result["createdby"].ToString());
                        project.createdusername = result["createdusername"].ToString();
                        project.projectmanager = Convert.ToInt16(result["projectmanager"].ToString());

                        var projectmembers = result["projectmembers"];
                        var stringlist = JsonConvert.SerializeObject(projectmembers);
                        var jArray = JArray.Parse(stringlist);
                        string Users = string.Empty;
                        foreach (string item in jArray)
                        {
                            Users = Users + item + ",";
                        }
                        Users = Users.Remove(Users.LastIndexOf(",")).ToString();
                        if (Users.ToString() != string.Empty)
                        {
                            int[] ints = Users.Split(',').Select(int.Parse).ToArray();
                            project.projectmembers = ints;
                        }

                        project.projectstatus = result["projectstatus"].ToString();
                        project.projecttype = result["projecttype"].ToString();

                        project.createdon = Convert.ToDateTime(result["createdon"]);
                    }
                    return project;
                }
                catch (Exception ex)
                {
                    throw ex;
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return null;
        }


        public async Task<JsonResult> projectlist(string organization)
        {
            List<Project> projectlist = new List<Project>();
            try
            {
                var search = Request.Form.GetValues("search[value]")[0];
                int startRec = Convert.ToInt32(Request.Form.GetValues("start")[0]);
                int pageSize = Convert.ToInt32(Request.Form.GetValues("length")[0]);
                int pmuserid = Convert.ToInt16(Session["LoggedInUserId"]);
                string projectnamesearch = string.Empty;
                if (search != "")
                {
                    projectnamesearch = $".has('project','projectname',containing('{search}'))";
                }
                var gremlinScript = string.Empty;//= $"g.V().hasLabel('project').project('projectid','projectname','startdate','enddate','noofresource','projectcost','createdby','createdusername','createdon','hashcode').by(id()).by(values('projectname')).by(values('startdate')).by(values('enddate')).by(values('noofresource')).by(values('projectcost')).by(values('createdby')).by(values('createdusername')).by(values('createdon')).by(values('hashcode'))";
                if (Convert.ToInt32(Session["RoleID"]) == (int)Role.ProjectManager || Convert.ToInt32(Session["RoleID"]) == (int)Role.User)
                {
                    //gremlinScript = $"g.V().has('project','projectmanager','{pmuserid}').or().has('project','projectmembers','{ pmuserid }')" + projectnamesearch + ".project('projectid','projectname','startdate','enddate','noofresource','projectcost','createdby','createdusername','createdon','hashcode','projectmanager','projectstatus','progress').by(id()).by(values('projectname')).by(values('startdate')).by(values('enddate')).by(values('noofresource')).by(values('projectcost')).by(values('createdby')).by(values('createdusername')).by(values('createdon')).by(values('hashcode')).by(values('projectmanager')).by(values('projectstatus')).by(values('progress'))";
                    gremlinScript = $"g.V().or(has('project','projectmanager','{ pmuserid }'),has('project','projectmembers','" + pmuserid + "'))" + projectnamesearch + ".project('projectid','projectname','startdate','enddate','noofresource','projectcost','createdby','createdusername','createdon','hashcode','projectmanager','projectstatus','progress').by(id()).by(values('projectname')).by(values('startdate')).by(values('enddate')).by(values('noofresource')).by(values('projectcost')).by(values('createdby')).by(values('createdusername')).by(values('createdon')).by(values('hashcode')).by(values('projectmanager')).by(values('projectstatus')).by(values('progress'))";
                    //gremlinScript = $"g.V().has('project','projectmanager','{pmuserid}')" + projectnamesearch + ".project('projectid','projectname','startdate','enddate','noofresource','projectcost','createdby','createdusername','createdon','hashcode','projectmanager','projectstatus','progress').by(id()).by(values('projectname')).by(values('startdate')).by(values('enddate')).by(values('noofresource')).by(values('projectcost')).by(values('createdby')).by(values('createdusername')).by(values('createdon')).by(values('hashcode')).by(values('projectmanager')).by(values('projectstatus')).by(values('progress'))";
                }
                else
                {
                    string projectmember = IGUtilities.getprojectmembers(pmuserid);
                    if (projectmember == "") projectmember = "''";
                    gremlinScript = $"g.V().has('project','projectmanager',within({projectmember}))" + projectnamesearch + ".project('projectid','projectname','startdate','enddate','noofresource','projectcost','createdby','createdusername','createdon','hashcode','projectmanager','projectstatus','progress').by(id()).by(values('projectname')).by(values('startdate')).by(values('enddate')).by(values('noofresource')).by(values('projectcost')).by(values('createdby')).by(values('createdusername')).by(values('createdon')).by(values('hashcode')).by(values('projectmanager')).by(values('projectstatus')).by(values('progress'))";
                }

                try
                {
                    var results = IGUtilities.ExecuteGremlinScript(gremlinScript);
                    var pList = JsonConvert.SerializeObject(results);                    
                    projectlist = JsonConvert.DeserializeObject<List<Project>>(pList);

                    var joinedData = from m in projectlist
                                     join r in db.tbl_user on m.projectmanager equals r.userid
                                     select new
                                     {
                                         projectid = m.projectid,
                                         projectname = m.projectname,
                                         startdate = m.startdate,
                                         enddate = m.enddate,
                                         type = m.type,
                                         noofresource = m.noofresource,
                                         projectcost = m.projectcost,
                                         createdby = m.projectmanager,
                                         createdusername = r.firstname + " " + r.lastname,
                                         createdon = m.createdon,
                                         projectmembers = m.projectmembers,
                                         organization = m.organization,
                                         projectstatus = m.projectstatus,
                                         projecttype = m.projecttype,
                                         hashcode = m.hashcode,
                                         progress = m.progress
                                     };

Cybereum/Views/Project/List.cshtml
@model List<SelectListItem>

@{
    ViewBag.Title = "Project List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="main-content">
    <div class="page-content">
        <div class="container-fluid">
            <div class="form-horizontal">
                <h4>Project List</h4>
                <hr />
            </div>
            @if (Convert.ToInt32(Session["RoleId"]) == 2 || Convert.ToInt32(Session["RoleId"]) == 4)
            {
                <p><button type="button" class="btn btn" style='background-color: #0D2136; color: white;' onclick="location.href='@Url.Action("AddEditProject", "Project")'">Add New</button></p>
            }            
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="table-responsive">
                                <table id="tblProject" class="display min-w850">
                                    <thead>
                                        <tr>
                                            <th>Project Name</th>
                                            <th>Start Date</th>
                                            <th>End Date</th>
                                            <th>Project Manager</th>
                                            <th>Created On</th>
                                            <th>Hash ID</th>
                                            <th>Edit</th>
                                            @*<th>Activity</th>*@
                                            <th>GANTT Chart</th>
                                        </tr>
                                    </thead>
                                    <tbody></tbody>
                                </table>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </div>
            @Scripts.Render("~/bundles/jquery")
            <style>
                .expand-column {
                    max-width: 70px;
                    overflow: hidden;
                    text-overflow: ellipsis;
                    white-space: nowrap;
                }
            </style>

            <script type="text/javascript">
    $(document).ajaxSend(function () {
        //$("#overlay").fadeIn(300);
    });

    $(document).ready(function () {
        $('#liUsers').addClass("active");

        //var reset = 0;
        var value = '@Request.RequestContext.HttpContext.Session["LoggedInUserId"]';
        var value1 = '@Request.RequestContext.HttpContext.Session["RoleId"]';
        var objFilter = {
            userid: value,
            roleid: value1            
        }

        $("#tblProject").DataTable(
        {
            processing: true,
            serverSide: true,
            filter: false,
            orderMulti: false,
            pageLength: 75,
            Sort: true,
            "ajax": {
                url: '@Url.Action("projectlist", "Project")',
                type: 'POST',
                data: objFilter
            },
            aLengthMenu: [[75, 100, 500, 1000, -1], [75, 100, 500, 1000, "All"]],
            iDisplayLength: 75,
            //scrollY: 400,
            aoColumnDefs: [{
                bSortable: false,
                aTargets: [-1, -2]
            }],
            "bAutoWidth": false,
            "info": true,
            columns: [
                { 'data': 'projectname', 'name': 'Project Name' },
                {
                    'data': 'startdate', 'name': 'Start Date',
                    'render': function (jsonDate) {
                        if (jsonDate != null) {
                            var date = new Date(parseInt(jsonDate.substr(6)));
                            var month = ("0" + (date.getMonth() + 1)).slice(-2);
                            return month + '-' + ("0" + date.getDate()).slice(-2) + '-' + date.getFullYear();
                        }
                        else {
                            return "";
                        }
                    }
                },
                {
                    'data': 'enddate', 'name': 'End Date',
                    'render': function (jsonDate) {
                        if (jsonDate != null) {
                            var date = new Date(parseInt(jsonDate.substr(6)));
                            var month = ("0" + (date.getMonth() + 1)).slice(-2);
                            return month + '-' + ("0" + date.getDate()).slice(-2) + '-' + date.getFullYear();
                        }
                        else {
                            return "";
                        }
                    }
                },
                { 'data': 'createdusername', 'name': 'Project Manager' },
                {
                    'data': 'createdon', 'name': 'Created On',
                    'render': function (jsonDate) {
                        if (jsonDate != null) {
                            var date = new Date(parseInt(jsonDate.substr(6)));
                            var month = ("0" + (date.getMonth() + 1)).slice(-2);
                            return month + '-' + ("0" + date.getDate()).slice(-2) + '-' + date.getFullYear();
                        }
                        else {
                            return "";
                        }
                    }
                },
                {
                    'data': 'hashcode', 'name': 'Hash ID', 'class': 'expand-column',
                    render: function (data, type, row) {
                        return '<span data-toggle="tooltip" title="' + data + '">' + data + "</span>";
                        //return '<span data-toggle="tooltip" title="' + data + '">' + data.length == 0 ? data : data.substr(0, 10) + '…' + '</span>';
                        //var trimdata = data.length > 10 ? data.substr(0, 10) + '…': data;
                        //return '<span data-toggle="tooltip" title="' + data + '">' + trimdata + '</span>';
                    }
                },
                {
                    "render": function (data, type, full, meta) {
                        var value1 = '@Request.RequestContext.HttpContext.Session["RoleId"]';
                        var value2 = '@Request.RequestContext.HttpContext.Session["LoggedInUserId"]';
                        if (value1 == '2' || value1 == '4' || value1 == '3') {
                            if (value2 == full.createdby || value1 == 4) {
                                return '<button class="btn btn" style="background-color: #0D2136; color: white;" onclick=getProject("' + full.projectid + '"); >Edit</button>';
                            }
                            else {
                                return '<button class="btn btn" style="background-color: #0D2136; color: white;" disabled="disabled" onclick=getProject("' + full.projectid + '"); >Edit</button>';
                            }
                        }
                        else {
                            return '<button class="btn btn" style="background-color: #0D2136; color: white;" disabled="disabled" onclick=getProject("' + full.projectid + '"); >Edit</button>';
                        }
                    }
                }
                //,
                //{
                //    data: 'projectname', render: function (data, type, row) {
                //        return "<button type='submit' onclick=GetMilestone('" + encodeURIComponent(row.projectid) + "'); class='btn btn' style='background-color: #0D2136; color: white;'>Activity</button>";
                //    }
                //}
                ,
                {
                    data: 'projectname', render: function (data, type, row) {
                        return "<button type='submit' onclick=GetChart('" + encodeURIComponent(row.projectid) + "'); class='btn btn' style='background-color: #0D2136; color: white;'>GANTT Chart</button>";
                    }
                }
            ],
            select: {
                style: 'multi',
                selector: 'td:first-child'
            },
        });
    });

    function getProject(id) {
        location.href = '@Url.Action("AddEditrecord", "Project", new { id = "id" })'.replace('id', id);
    }

    function GetMilestone(projectid) {
        location.href = '@Url.Action("Index", "Activity")?projectid=' + projectid + '';
    }

    function GetChart(projectid) {
        @*location.href = '@Url.Action("GANTTChart", "Home")?projectid=' + projectid + '';*@
        location.href = '@Url.Action("GanttChart", "Project")?projectid=' + projectid + '';
    }


    function GetTask(projectid) {
        location.href = '@Url.Action("Index", "Task")?projectid=' + projectid + '';
    }

    function EditData(projectid) {
        $.ajax(
        {
            url: '@Url.Action("AddEditProject", "Project")?Id=' + projectid,
            contentType: 'application/json; charset=utf-8',
            datatype: 'json',
            async: true,
            data: {
                datuserid: projectid
            },
            type: "GET",
            success: function (response) {
                $("#overlay").fadeOut(300);
                if (response == "Success")
                    @*window.location = '@Url.Action("Users", "User")?userid=' + userid;
                else
                    msg(response, 'info');*@
                    msg("Record edited successfully", "info");
                window.location.reload();
            }
        });
    }

    function DeleteData(id) {
        if (confirm("Are you sure you want to delete this record?")) {
            $.ajax({
                url: '@Url.Action("DeleteUser", "User")?id=' + id,
                type: "GET",
                dataType: "JSON",
                data: '{}',
                success: function (response) {
                    msg("Record deleted successfully", "info");
                    window.location.reload();
                }
            });
        }
        return false;
    }

    function msg(strMsg, mode) {
        $.notify(strMsg, mode, { globalPosition: 'top center', clickToHide: true, autoHide: false });
    }
            </script>

Cybereum/Views/Project/OrganizationProjectList.cshtml
@model List<SelectListItem>

@{
    ViewBag.Title = "Project List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="main-content">

    <div class="page-content">
        <div class="container-fluid">
            <div class="form-horizontal">
                <h4>Project List</h4>
                <hr />
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="table-responsive">
                                <table id="tblProject" class="table table-hover mb-0" width="100%">
                                    <thead>
                                        <tr>
                                            <th>Project Name</th>
                                            <th>Start Date</th>
                                            <th>End Date</th>
                                            <th>Project Manager</th>
                                            <th>Project Status</th>
                                            <th>Created On</th>
                                            <th>Hash ID</th>
                                            @*<th>GANTT Chart</th>*@
                                        </tr>
                                    </thead>
                                    <tbody></tbody>
                                </table>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@Scripts.Render("~/bundles/jquery")
<style>
    .expand-column {
        max-width: 70px;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
    }
</style>

<script type="text/javascript">
    $(document).ajaxSend(function () {
        //$("#overlay").fadeIn(300);
    });

    $(document).ready(function () {
        $('#liUsers').addClass("active");

        var value = '@Request.RequestContext.HttpContext.Session["Organization"]';
        var objFilter = {
            organization: value
        }
        debugger;
        $("#tblProject").DataTable(
        {
            processing: true,
            serverSide: true,
            filter: false,
            orderMulti: false,
            paging: false,
            Sort: true,
            "ajax": {
                url: '@Url.Action("projectlistfororganization", "Project")',
                type: 'POST',
                data: objFilter
            },
            aLengthMenu: [[75, 100, 500, 1000, -1], [75, 100, 500, 1000, "All"]],
            iDisplayLength: 75,
            //scrollY: 400,
            aoColumnDefs: [{
                bSortable: false,
                aTargets: [-1, -2]
            }],
            "bAutoWidth": false,
            "info": true,
            columns: [
                { 'data': 'projectname', 'name': 'Project Name' },
                {
                    'data': 'startdate', 'name': 'Start Date',
                    'render': function (jsonDate) {
                        if (jsonDate != null) {
                            var date = new Date(parseInt(jsonDate.substr(6)));
                            var month = ("0" + (date.getMonth() + 1)).slice(-2);
                            return month + '-' + ("0" + date.getDate()).slice(-2) + '-' + date.getFullYear();
                        }
                        else {
                            return "";
                        }
                    }
                },
                {
                    'data': 'enddate', 'name': 'End Date',
                    'render': function (jsonDate) {
                        debugger;
                        if (jsonDate != null) {
                            var date = new Date(parseInt(jsonDate.substr(6)));
                            var month = ("0" + (date.getMonth() + 1)).slice(-2);
                            return month + '-' + ("0" + date.getDate()).slice(-2) + '-' + date.getFullYear();
                        }
                        else {
                            return "";
                        }
                    }
                },
                { 'data': 'createdusername', 'name': 'Project Manager' },
                { 'data': 'projectstatus', 'name': 'Project Status' },
                {
                    'data': 'createdon', 'name': 'Created On',
                    'render': function (jsonDate) {
                        if (jsonDate != null) {
                            var date = new Date(parseInt(jsonDate.substr(6)));
                            var month = ("0" + (date.getMonth() + 1)).slice(-2);
                            return month + '-' + ("0" + date.getDate()).slice(-2) + '-' + date.getFullYear();
                        }
                        else {
                            return "";
                        }
                    }
                },
                {
                    'data': 'hashcode', 'name': 'Hash ID', 'class': 'expand-column',
                    render: function (data, type, row) {
                        debugger;
                        return '<span data-toggle="tooltip" title="' + data + '">' + data + "</span>";
                        //return '<span data-toggle="tooltip" title="' + data + '">' + data.length == 0 ? data : data.substr(0, 10) + '…' + '</span>';
                        //var trimdata = data.length > 10 ? data.substr(0, 10) + '…': data;
                        //return '<span data-toggle="tooltip" title="' + data + '">' + trimdata + '</span>';
                    }
                }
            ],
            select: {
                style: 'multi',
                selector: 'td:first-child'
            },
        });
    });


    function msg(strMsg, mode) {
        $.notify(strMsg, mode, { globalPosition: 'top center', clickToHide: true, autoHide: false });
    }
</script>